---
title: skytest
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  menu_corporate:
    title: menu_corporate
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: menu_corporate
  values:
<<<<<<< HEAD
    layout:
    submenu:
     title_submenu:
     url_submenu:
=======
    layout: 
    developers: 
    contact_us: 
    news_events: 
>>>>>>> fdb118a2cebd38d93e448abf77e2dc5add90eb85
permalink: pretty
